title:            Piperod- UPRM
description:      In this blog I will be postings related to my master in Scientific Computation at UPRM(RUM) and other fields.
disqus_shortname: Piperod 
reading_time:     true
words_per_minute: 200
logo:             images/logo.png
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use 
url: https://piperod.github.io

menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'
  - title: 'tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Fun Stuff'
    url: '#'
    submenu:
      

# Owner/author information
owner:
  name:           Ivan Felipe Rodriguez
  site:           https://piperod.github.io
  avatar:         images/avatar.jpg
  bio:            "Colombian.LDS member(mormon).Mathematician. Teacher. Student at RUM: Master in Scientific Computing. Guitar. Geek xd.  "
  email:          ifelipe.rodriguez@hotmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: piperod
  facebook: Ivan Felipe Rodriguez
  github: piperod
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +AronBordin
  google_plus:    +alcuadrado91

social:
  - title: "github"
    url: "https://github.com/piperod"

  - title: "facebook"
    url: "https://www.facebook.com/ifelipe.rodriguez"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
